name: Update Newest List of Leecode
on: 
  push:
  schedule:
    - cron: "00 19 * * 1"    #run every week on Mondays at 19:00 UTC
jobs:
  daily-code-list-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pandas
          pip install gitpython
        shell: bash
      - name: Run autoLs
        run: |
          python ActionPy/autoLs.py
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add .
          git commit -m "DailyCodeList updated by autoLs"
          git push
        shell: bash
      - name: result check
        if: failure()
        run: |
          echo "[Error] 由於本次沒有任何更新，本次更新失敗。
          exit 1