name: cpp Build auto Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cpp20-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: Init unit test
      run: |
        sudo apt-get update
        sudo apt-get install build-essential gdb
        gcc --version
        g++ --version
        gdb --version
        pip install pytest
        python ActionPy/SetUpForTest/setupforbuild20.py
    - name: Start test_cpp_20_build
      run: |
        pytest ActionPy/test_cpp_20_build.py
      shell: bash