name: cpp Build auto Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cpp17-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: Init unit test
      run: |
        pip install pytest
        python ActionPy/SetUpForTest/setupforbuild.py
        
    - name: Start test_cpp_20_build
      run: |
        pytest ActionPy/test_cpp_20_build.py
      shell: bash