name: cpp17 Build auto Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cpp17-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install c++ dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake
    - name: Init unit test
      run: |
        pip install pytest
        py ActionPy/SetUpForTest/setupforbuild17.py
    - name: Start test_cpp_17_build
      run: |
        pytest ActionPy/test_cpp_17_build.py