name: cpp Build auto Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cpp17-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        c_compiler: [gcc, clang]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Init unit test
      run: |
        pip install pytest
        python ActionPy/SetUpForTest/setupforbuild20.py
        
    - name: Start test_cpp_20_build
      run: |
        gcc --version
        pytest ActionPy/test_cpp_20_build.py
      shell: bash