name: Metadata Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-metadata-Format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install pytest
        import os
    - name: Test Metadata Format
      run: |
        python -c "import os
          markdown_files = [os.path.join('leetcode', f) for f in os.listdir('leetcode') if f.endswith('.md')]
          for file_path in markdown_files:
            pytest tests/test_metadata_format.py::test_metadata_format[$file_path]
        "