name: Update Newest List of Leecode Problems
on: 
  schedule:
    - cron: "00 19 * * *"    #runs at 19:00 UTC everyday

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Update Newest List of Leecode Problems
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch num squared
        id: get_square
        uses: ./ # Uses an action in the root directory
        # or use a released GitHub Action
        # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
        with:
          num: 11
      - name: Print the square
        run: echo "${{ steps.get_square.outputs.num_squared }}"